general edits
flexcompute-readthedocs/Flow360Documentation pull request #39
Opened 2022-05-23 19:18 UTC by PeterZFarkas

2022-05-23 19:20 UTC, cjdoolittle commented on docs/source/examples/om6_wing_webUI.rst
> +- Alpha = 3.06 |deg|
CJ adding comment

2022-06-08 14:42 UTC, will-flex requested changes

2022-06-08 14:42 UTC, will-flex commented on docs/source/preprocessing/manualMeshing.rst
> +    -   Boundaries **must** be exported as `“Elements_t” <https://cgns.github.io/CGNS_docs_current/sids/gridflow.html>`_ type, which contains connectivity information necessary in Flow360
Recommend adding #Elements to link: https://cgns.github.io/CGNS_docs_current/sids/gridflow.html#Elements

Directs user straight to Elements_t definition.

2022-06-08 14:44 UTC, will-flex approved these changes

2022-06-08 14:46 UTC, will-flex approved these changes

2022-06-08 14:48 UTC, will-flex submitted a review, later dismissed

2022-06-08 18:50 UTC, will-flex submitted a review, later dismissed

2022-06-23 05:37 UTC, cjdoolittle commented on docs/source/examples/om6_wing_webUI.rst
> +- Alpha = 3.06 |deg|
fix in sec. 1.2 also

2022-06-23 05:45 UTC, cjdoolittle commented on docs/source/preprocessing/manualMeshing.rst
> +    -   Boundaries **must** be exported as `“Elements_t” <https://cgns.github.io/CGNS_docs_current/sids/gridflow.html>`_ type, which contains connectivity information necessary in Flow360
agreed, add #Elements. Let's remove the HDF5 Wikipedia link, however.

2022-06-23 06:47 UTC, cjdoolittle requested changes

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/examples/om6_wing_webUI.rst
>  The Onera M6 wing is a classic CFD validation case for external flows because of its simple geometry combined with complexities of transonic flow (i.e. local supersonic flow, shocks, and turbulent bo
"The geometry parameters are" > "The geometry parameters of the model are"

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/examples/om6_wing_webUI.rst
> +- Reference area = 1.15315 m^2
format to superscript

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/examples/om6_wing_pyAPI.rst
>  The Onera M6 wing is a classic CFD validation case for external flows because of its simple geometry combined with complexities of transonic flow (i.e. local supersonic flow, shocks, and turbulent bo
apply same changes as in om6_wing_webUI.rst here. You'll see in my recent commit that there are a number of text edits throughout the page. Please try to apply these changes where applicable.

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/examples/om6_wing_webUI.rst
"113K nodes and 663K" > "113k nodes and 663k"

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/preprocessing/automatedMeshing.rst
> +The surface mesher takes the geometry file and configuration `JSON <https://en.wikipedia.org/wiki/JSON>`_ file as input parameters and generates a surface mesh. The meshing configuration file (or dic
revert change

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/solverConfiguration/betTable.csv
> +volumeName@ Empty@ [string] Name of the mesh-block in which the BET-Disk is located. If unspecified, default will be the highest-level mesh-block. Used for specifying a BET-disk within a moving refer
I think that volumeName is only available in a beta-release, let's remove for now. If someone asked you to include this, then disregard and keep it in.

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/solverConfiguration/solverConfiguration.rst
> +   | quadraticConstitutiveRelation  |      FALSE      | Use quadratic constitutive relation for turbulence shear stress tensor instead of Boussinesq Approximation                                |
I think that volumeName is only available in a beta-release, let's remove for now. If someone asked you to include this, then disregard and keep it in.

2022-06-23 06:47 UTC, cjdoolittle commented on docs/source/capabilities/bladeElementTheory.rst
> +   The x-, y-, z-component of Disk[diskID]_Force and Disk[diskID]_Moment is based on the inertial frame of reference, which is defined in the mesh file. The inertial frame of reference is fixed at th
I don't fully understand this comment, can we revise?

2022-06-30 21:57 UTC, cjdoolittle approved these changes

2022-07-04 12:55 UTC, merged